# Generated by Django 4.2.5 on 2023-11-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenDate', models.DateField(auto_created=True)),
                ('content', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('likeNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likes.like')),
            ],
        ),
    ]
